# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lists', '0005_list_item_unique_together'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='item',
            order_with_respect_to='list',
        ),
    ]
